services:
  postgres:
    image: postgres:16-alpine
    container_name: cfmn-dev-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      PGHOST: ${DB_HOST}
    volumes:
      # This volume persists the database data
      - postgres-data-dev:/var/lib/postgresql/data
      # This script will run on initialization from the /database directory
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"



volumes:
  postgres-data-dev:
    name: postgres-data-dev
